name: MeritRank Badge Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate config
        shell: pwsh
        run: pwsh -File scripts/validate_config.ps1 -ConfigPath config/meritrank.config.json

      - name: Validate registry
        shell: pwsh
        run: pwsh -File scripts/validate_registry.ps1 -RepoRoot .

      - name: Ensure out dir
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path out | Out-Null

      - name: Registry ingest
        shell: pwsh
        run: pwsh -File scripts/registry_ingest.ps1 -RepoRoot . -OutDir ./out

      - name: Mapper (demo + TODO scan)
        shell: pwsh
        run: pwsh -File scripts/mapper_demo.ps1 -RepoRoot . -OutDir ./out

      - name: Scorer
        shell: pwsh
        run: pwsh -File scripts/score_demo.ps1 -MapPath ./out/map_demo.json -OutDir ./out -ConfigPath config/meritrank.config.json

      - name: Prepare pages artifact (badge + index)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path public | Out-Null
          Copy-Item out/badge.json public/badge.json -Force
          $html = @(
            '<!doctype html><meta charset="utf-8"><title>MeritRank</title>',
            '<h1>MeritRank</h1>',
            '<p><img alt="MeritRank" src="https://img.shields.io/endpoint?url=https://rickballard.github.io/MeritRank/badge.json&amp;cacheSeconds=300"></p>',
            '<ul>',
            '  <li><a href="badge.json">badge.json</a></li>',
            '</ul>'
          )
          [IO.File]::WriteAllLines("public/index.html", $html, [Text.UTF8Encoding]::new($true))

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: badge
    if: github.event_name != 'pull_request'
    # keep Pages concurrency isolated to deploy-only
    concurrency:
      group: pages
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
